spring:
  datasource:
    url: jdbc:sqlite:C:\数据库文件\tushen.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

# MyBatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true