spring:
  datasource:
    url: jdbc:sqlite::resource:data/tushen.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true